package com.example.studentenradar.contract.model;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

@Embeddable
public class StudentContractId implements Serializable {

    @Column(name = "student_id")
    int studentId;

    @Column(name = "contract_id")
    int contractId;

    public StudentContractId(){
    }

    public StudentContractId(int studentId, int contractId) {
        this.studentId = studentId;
        this.contractId = contractId;
    }

    public int getStudentId() {
        return studentId;
    }

    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }

    public int getContractId() {
        return contractId;
    }

    public void setContractId(int contractId) {
        this.contractId = contractId;
    }

    @Override // Generated by vscode 
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + studentId;
        result = prime * result + contractId;
        return result;
    }

    @Override // Generated by vscode 
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        StudentContractId other = (StudentContractId) obj;
        if (studentId != other.studentId || contractId != other.contractId)
            return false;
        if (contractId != other.contractId)
            return false;
        return true;
    } 
}
